import type {Metadata} from "next";
import "./globals.css";
import Providers from "@/components/Providers";
import {ReactNode} from "react";
import TopNav from "@/components/navbar/TopNav";

export const metadata: Metadata = {
    title: "My own tinder",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: ReactNode;
}>) {
    return (
        <html suppressHydrationWarning lang="en">
        <body>
        <Providers>
            <TopNav/>
            <main className='container mx-auto p-10'>
                {children}
            </main>
        </Providers>
        </body>
        </html>
    );
}
