import type { Metadata } from 'next';
import './globals.css';
import Providers from '@/components/Providers';
import { ReactNode } from 'react';
import TopNav from '@/components/navbar/TopNav';
import { auth } from '@/auth';

export const metadata: Metadata = {
  title: 'My own tinder',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }: Readonly<{ children: ReactNode }>) {
  const session = await auth();
  const userId = session?.user?.id || null;
  const profileComplete = session?.user.profileComplete as boolean;
  return (
    <html suppressHydrationWarning lang="en">
      <body suppressHydrationWarning>
        <Providers userId={userId} profileComplete={profileComplete}>
          <TopNav />
          <main className="mx-auto w-full max-w-screen-xl px-4 pt-6 sm:pt-10 lg:px-8">
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
