import type { Metadata } from 'next';
import './globals.css';
import Providers from '@/components/Providers';
import { NextIntlClientProvider } from 'next-intl';
import { notFound } from 'next/navigation';
import { ReactNode } from 'react';
import TopNav from '@/components/navbar/TopNav';
import { auth } from '@/auth';

export const metadata: Metadata = {
  title: 'My own tinder',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{ children: ReactNode; params: Promise<{ locale: string }> }>) {
  const { locale } = await params;
  if (!['en', 'uk'].includes(locale)) {
    notFound();
  }
  const messages = (await import(`@/translations/${locale}.json`)).default;
  const session = await auth();
  const userId = session?.user?.id || null;
  const profileComplete = session?.user.profileComplete as boolean;

  return (
    <html suppressHydrationWarning lang={locale}>
      <body suppressHydrationWarning>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <Providers userId={userId} profileComplete={profileComplete}>
            <TopNav locale={locale} />
            <main className="mx-auto w-full max-w-screen-xl px-4 pt-6 sm:pt-10 lg:px-8">
              {children}
            </main>
          </Providers>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
